### PR TITLE
Fixes for both transient override bugs.

### LINKED ISSUE #27: Transient boot selection is only cleared if both images are valid.
check_for_override() is only called if both images are valid and therefore the transient boot selection will not be cleared if only one image is valid. This makes it a potentially lingering preference.

The state of transient override at boot time is a candidate for inclusion in a "boot decision log" along with other inputs.
It may be better to compute the full set of inputs prior to using them and then passing them along to the next stage.

### LINKED ISSUE #28: Implement acknowledgement of transient boot override
When bootleby responds to a transient boot override token at the special RAM location, it destroys the token to ensure that it only applies once.

We need to make sure that the destroy operation allows the firmware that's booted subsequently to notice that an override happened. I _think_ the existing logic may already be sufficient, but this bug is a reminder to check.

### PR DESCRIPTION
**Pull request by cbiffle**
This fixes #27 by moving the transient override check to an unconditional codepath, and fixes #28 by recording what transient override was observed (in addition to the fact that one _was_ observed, which already worked).

For more details see the individual commit messages.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -464,8 +465,9 @@ pub fn check_transient_override(buffer: &mut [u8; 32]) -> Option<SlotId> {
         None
     };
 
-    if choice.is_some() {
+    if let Some(slot) = choice {
         buffer.fill(0);
+        buffer[0] = if slot == SlotId::A { 0 } else { 1 };
```
Comment (lzrd) [inline src/lib.rs:470]: In order for Hubris-now to know what Hubris-then set the transient request to, Hubris then has to put PREFER_SLOT_A, PREFER_SLOT_B or something not equal to either of those or zeros or zeros+1.
If the not-any-of-those-values survives, then Hubris-then's "message of didn't use the feature" gets passed through.
If all-zeros or all-zeros+1 is seen, then Hubris-then might have used the feature or maybe no Hubris instance since long ago has cleaned up.
This can be solved in Hubris pre-kernel by harvesting the value and setting that area to some constant.
However, if anyone is zeroing or otherwise initializing the transient override buffer, then the reading can still be ambiguous.

I would prefer that the transient preference buffer always be written with one of three values:
  - all zeros + 2 indicates that there had been no transient preference expressed.
  - all zeros indicates SlotId::A was preferred
  - all zeros + 1 indicates SlotId::B was preferred.
...or something similar. The leading zeros can be reserved by bootleby and ignored by stage1/Hubris until defined. This is the way.

**Review by lzrd — APPROVED** [review]
LGTM
